//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intersoft.CISSA.UserApp.Resources.Form", typeof(Form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие.
        /// </summary>
        public static string ActionColumn {
            get {
                return ResourceManager.GetString("ActionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в данных контекста!.
        /// </summary>
        public static string AppContextDataError {
            get {
                return ResourceManager.GetString("AppContextDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        public static string AskTitle {
            get {
                return ResourceManager.GetString("AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно указан тип кнопки.
        /// </summary>
        public static string ButtonTypeError {
            get {
                return ResourceManager.GetString("ButtonTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор действия.
        /// </summary>
        public static string ChoseAction {
            get {
                return ResourceManager.GetString("ChoseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуальный элемент не найден!.
        /// </summary>
        public static string ControlNotFound {
            get {
                return ResourceManager.GetString("ControlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в типе элемента управления.
        /// </summary>
        public static string ControlTypeError {
            get {
                return ResourceManager.GetString("ControlTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий статус.
        /// </summary>
        public static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История состояний документа.
        /// </summary>
        public static string DocStateHistory {
            get {
                return ResourceManager.GetString("DocStateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс документа не определен!.
        /// </summary>
        public static string DocumentClassNotDefined {
            get {
                return ResourceManager.GetString("DocumentClassNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ не найден для отображения.
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string EditForm {
            get {
                return ResourceManager.GetString("EditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное поле не может быть пустым! Введите значение..
        /// </summary>
        public static string FieldCannotBeenEmpty {
            get {
                return ResourceManager.GetString("FieldCannotBeenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Критерии поиска.
        /// </summary>
        public static string FilterCriteries {
            get {
                return ResourceManager.GetString("FilterCriteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма не найдена!.
        /// </summary>
        public static string FormNotFound {
            get {
                return ResourceManager.GetString("FormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма или документ не найдены!.
        /// </summary>
        public static string FormOrDocumentNotFound {
            get {
                return ResourceManager.GetString("FormOrDocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в типе формы!.
        /// </summary>
        public static string FormTypeError {
            get {
                return ResourceManager.GetString("FormTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата передана в неверном формате.
        /// </summary>
        public static string InvalidDateTimeFormat {
            get {
                return ResourceManager.GetString("InvalidDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение передано в неверном формате.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число передано в неверном формате.
        /// </summary>
        public static string InvalidNumberFormat {
            get {
                return ResourceManager.GetString("InvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDocument.
        /// </summary>
        public static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string NoColumn {
            get {
                return ResourceManager.GetString("NoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма параметра.
        /// </summary>
        public static string ParamFormTitle {
            get {
                return ResourceManager.GetString("ParamFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string PositionTitle {
            get {
                return ResourceManager.GetString("PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Requery {
            get {
                return ResourceManager.GetString("Requery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string ResetForm {
            get {
                return ResourceManager.GetString("ResetForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во строк.
        /// </summary>
        public static string RowCount {
            get {
                return ResourceManager.GetString("RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор.
        /// </summary>
        public static string SelectColumn {
            get {
                return ResourceManager.GetString("SelectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата установки.
        /// </summary>
        public static string SetDateColumn {
            get {
                return ResourceManager.GetString("SetDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string StateColumn {
            get {
                return ResourceManager.GetString("StateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История состояний.
        /// </summary>
        public static string StateHistory {
            get {
                return ResourceManager.GetString("StateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата установки статуса.
        /// </summary>
        public static string StateSetDate {
            get {
                return ResourceManager.GetString("StateSetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма не явлется табличной или заданы не все параметры.
        /// </summary>
        public static string TableFormError {
            get {
                return ResourceManager.GetString("TableFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Excel.
        /// </summary>
        public static string ToExcel {
            get {
                return ResourceManager.GetString("ToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл для отправки.
        /// </summary>
        public static string UploadForm {
            get {
                return ResourceManager.GetString("UploadForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь, изменивший состояние.
        /// </summary>
        public static string UserNameColumn {
            get {
                return ResourceManager.GetString("UserNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Без статуса].
        /// </summary>
        public static string WithoutState {
            get {
                return ResourceManager.GetString("WithoutState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
