//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.BizService.Contract")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgUnitNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgUnitName {
            get {
                return this.OrgUnitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgUnitNameField, value) != true)) {
                    this.OrgUnitNameField = value;
                    this.RaisePropertyChanged("OrgUnitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizResult", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.BizService.Contract")]
    [System.SerializableAttribute()]
    public partial class BizResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.BizResult.BizResultType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.BizResult.BizResultType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BizResult.BizResultType", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.BizService.Contract")]
        public enum BizResultType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Warning = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Message = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            User = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Form = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Report = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Query = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Action = 7,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizObject", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.BizService.Contract")]
    [System.SerializableAttribute()]
    public partial class BizObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.BizObject[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.BizObjectType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.BizObject[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DefId {
            get {
                return this.DefIdField;
            }
            set {
                if ((this.DefIdField.Equals(value) != true)) {
                    this.DefIdField = value;
                    this.RaisePropertyChanged("DefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.BizObjectType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizObjectType", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.BizService.Contract")]
    public enum BizObjectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Form = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Report = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Query = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Action = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DocumentDef = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportDef = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueryDef = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Panel = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bar = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Button = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Edit = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComboBox = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        List = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Memo = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RadioGroup = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RadioItem = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CheckBox = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TableGrid = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DetailGrid = 21,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizControlData", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.BizService.Contract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.Doc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.CurrencyAttribute[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.CurrencyAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.AttrDef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.DocDef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.EnumDef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.TypeDef))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.DocAttribute[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.DocAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.EnumAttribute[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.EnumAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.FloatAttribute[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.FloatAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.IntAttribute[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.IntAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.TextAttribute[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.TextAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.UserInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.BizResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.BizResult.BizResultType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.BizObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.BizObject[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestProject1.ServiceReference.BizObjectType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Drawing.Image))]
    public partial class BizControlData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AttributeDefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid DocumentDefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EnumDefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EnumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Drawing.Image ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ProcessDefIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AttributeDefId {
            get {
                return this.AttributeDefIdField;
            }
            set {
                if ((this.AttributeDefIdField.Equals(value) != true)) {
                    this.AttributeDefIdField = value;
                    this.RaisePropertyChanged("AttributeDefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocumentDefId {
            get {
                return this.DocumentDefIdField;
            }
            set {
                if ((this.DocumentDefIdField.Equals(value) != true)) {
                    this.DocumentDefIdField = value;
                    this.RaisePropertyChanged("DocumentDefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EnumDefId {
            get {
                return this.EnumDefIdField;
            }
            set {
                if ((this.EnumDefIdField.Equals(value) != true)) {
                    this.EnumDefIdField = value;
                    this.RaisePropertyChanged("EnumDefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EnumId {
            get {
                return this.EnumIdField;
            }
            set {
                if ((this.EnumIdField.Equals(value) != true)) {
                    this.EnumIdField = value;
                    this.RaisePropertyChanged("EnumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Image Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ProcessDefId {
            get {
                return this.ProcessDefIdField;
            }
            set {
                if ((this.ProcessDefIdField.Equals(value) != true)) {
                    this.ProcessDefIdField = value;
                    this.RaisePropertyChanged("ProcessDefId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doc", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class Doc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.CurrencyAttribute[] AttrCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.DocAttribute[] AttrDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.EnumAttribute[] AttrEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.FloatAttribute[] AttrFloatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.IntAttribute[] AttrIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.TextAttribute[] AttrTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.DocDef DocDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.CurrencyAttribute[] AttrCurrency {
            get {
                return this.AttrCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrCurrencyField, value) != true)) {
                    this.AttrCurrencyField = value;
                    this.RaisePropertyChanged("AttrCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.DocAttribute[] AttrDoc {
            get {
                return this.AttrDocField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDocField, value) != true)) {
                    this.AttrDocField = value;
                    this.RaisePropertyChanged("AttrDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.EnumAttribute[] AttrEnum {
            get {
                return this.AttrEnumField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrEnumField, value) != true)) {
                    this.AttrEnumField = value;
                    this.RaisePropertyChanged("AttrEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.FloatAttribute[] AttrFloat {
            get {
                return this.AttrFloatField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrFloatField, value) != true)) {
                    this.AttrFloatField = value;
                    this.RaisePropertyChanged("AttrFloat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.IntAttribute[] AttrInt {
            get {
                return this.AttrIntField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrIntField, value) != true)) {
                    this.AttrIntField = value;
                    this.RaisePropertyChanged("AttrInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.TextAttribute[] AttrText {
            get {
                return this.AttrTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrTextField, value) != true)) {
                    this.AttrTextField = value;
                    this.RaisePropertyChanged("AttrText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.DocDef DocDef {
            get {
                return this.DocDefField;
            }
            set {
                if ((object.ReferenceEquals(this.DocDefField, value) != true)) {
                    this.DocDefField = value;
                    this.RaisePropertyChanged("DocDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyAttribute", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class CurrencyAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.AttrDef AttrDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.AttrDef AttrDef {
            get {
                return this.AttrDefField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDefField, value) != true)) {
                    this.AttrDefField = value;
                    this.RaisePropertyChanged("AttrDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttrDef", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class AttrDef : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.DocDef DocDefTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.EnumDef EnumDefTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.DocDef OwnerDocDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.TypeDef TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.DocDef DocDefType {
            get {
                return this.DocDefTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocDefTypeField, value) != true)) {
                    this.DocDefTypeField = value;
                    this.RaisePropertyChanged("DocDefType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.EnumDef EnumDefType {
            get {
                return this.EnumDefTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnumDefTypeField, value) != true)) {
                    this.EnumDefTypeField = value;
                    this.RaisePropertyChanged("EnumDefType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.DocDef OwnerDocDef {
            get {
                return this.OwnerDocDefField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerDocDefField, value) != true)) {
                    this.OwnerDocDefField = value;
                    this.RaisePropertyChanged("OwnerDocDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.TypeDef Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocDef", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class DocDef : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumDef", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class EnumDef : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeDef", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class TypeDef : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocAttribute", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class DocAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.AttrDef AttrDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.AttrDef AttrDef {
            get {
                return this.AttrDefField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDefField, value) != true)) {
                    this.AttrDefField = value;
                    this.RaisePropertyChanged("AttrDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumAttribute", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class EnumAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.AttrDef AttrDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.AttrDef AttrDef {
            get {
                return this.AttrDefField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDefField, value) != true)) {
                    this.AttrDefField = value;
                    this.RaisePropertyChanged("AttrDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FloatAttribute", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class FloatAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.AttrDef AttrDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.AttrDef AttrDef {
            get {
                return this.AttrDefField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDefField, value) != true)) {
                    this.AttrDefField = value;
                    this.RaisePropertyChanged("AttrDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntAttribute", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class IntAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.AttrDef AttrDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.AttrDef AttrDef {
            get {
                return this.AttrDefField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDefField, value) != true)) {
                    this.AttrDefField = value;
                    this.RaisePropertyChanged("AttrDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextAttribute", Namespace="http://schemas.datacontract.org/2004/07/Intersoft.CISSA.DataAccessLayer.Model")]
    [System.SerializableAttribute()]
    public partial class TextAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestProject1.ServiceReference.AttrDef AttrDefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestProject1.ServiceReference.AttrDef AttrDef {
            get {
                return this.AttrDefField;
            }
            set {
                if ((object.ReferenceEquals(this.AttrDefField, value) != true)) {
                    this.AttrDefField = value;
                    this.RaisePropertyChanged("AttrDef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IUserManager")]
    public interface IUserManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/GetUserInfo", ReplyAction="http://tempuri.org/IUserManager/GetUserInfoResponse")]
        TestProject1.ServiceReference.UserInfo GetUserInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManager/ChangeUserPassword", ReplyAction="http://tempuri.org/IUserManager/ChangeUserPasswordResponse")]
        TestProject1.ServiceReference.BizResult ChangeUserPassword(string oldPassword, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagerChannel : TestProject1.ServiceReference.IUserManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagerClient : System.ServiceModel.ClientBase<TestProject1.ServiceReference.IUserManager>, TestProject1.ServiceReference.IUserManager {
        
        public UserManagerClient() {
        }
        
        public UserManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestProject1.ServiceReference.UserInfo GetUserInfo() {
            return base.Channel.GetUserInfo();
        }
        
        public TestProject1.ServiceReference.BizResult ChangeUserPassword(string oldPassword, string newPassword) {
            return base.Channel.ChangeUserPassword(oldPassword, newPassword);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IPresentationManager")]
    public interface IPresentationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationManager/GetBizObject", ReplyAction="http://tempuri.org/IPresentationManager/GetBizObjectResponse")]
        TestProject1.ServiceReference.BizObject GetBizObject(System.Guid userId, System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationManager/GetBizObjectType", ReplyAction="http://tempuri.org/IPresentationManager/GetBizObjectTypeResponse")]
        TestProject1.ServiceReference.BizObjectType GetBizObjectType(System.Guid userId, System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationManager/GetBizObjectChildren", ReplyAction="http://tempuri.org/IPresentationManager/GetBizObjectChildrenResponse")]
        TestProject1.ServiceReference.BizObject[] GetBizObjectChildren(System.Guid userId, System.Guid objectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationManager/GetMainFormObjects", ReplyAction="http://tempuri.org/IPresentationManager/GetMainFormObjectsResponse")]
        TestProject1.ServiceReference.BizObject[] GetMainFormObjects(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationManager/GetBizControlData", ReplyAction="http://tempuri.org/IPresentationManager/GetBizControlDataResponse")]
        TestProject1.ServiceReference.BizControlData GetBizControlData(System.Guid userId, System.Guid controlId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresentationManager/ExecuteBizAction", ReplyAction="http://tempuri.org/IPresentationManager/ExecuteBizActionResponse")]
        TestProject1.ServiceReference.BizResult ExecuteBizAction(System.Guid userId, System.Guid actionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPresentationManagerChannel : TestProject1.ServiceReference.IPresentationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresentationManagerClient : System.ServiceModel.ClientBase<TestProject1.ServiceReference.IPresentationManager>, TestProject1.ServiceReference.IPresentationManager {
        
        public PresentationManagerClient() {
        }
        
        public PresentationManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PresentationManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresentationManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresentationManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestProject1.ServiceReference.BizObject GetBizObject(System.Guid userId, System.Guid objectId) {
            return base.Channel.GetBizObject(userId, objectId);
        }
        
        public TestProject1.ServiceReference.BizObjectType GetBizObjectType(System.Guid userId, System.Guid objectId) {
            return base.Channel.GetBizObjectType(userId, objectId);
        }
        
        public TestProject1.ServiceReference.BizObject[] GetBizObjectChildren(System.Guid userId, System.Guid objectId) {
            return base.Channel.GetBizObjectChildren(userId, objectId);
        }
        
        public TestProject1.ServiceReference.BizObject[] GetMainFormObjects(System.Guid userId) {
            return base.Channel.GetMainFormObjects(userId);
        }
        
        public TestProject1.ServiceReference.BizControlData GetBizControlData(System.Guid userId, System.Guid controlId) {
            return base.Channel.GetBizControlData(userId, controlId);
        }
        
        public TestProject1.ServiceReference.BizResult ExecuteBizAction(System.Guid userId, System.Guid actionId) {
            return base.Channel.ExecuteBizAction(userId, actionId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDocManager")]
    public interface IDocManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocManager/DocumentLoad", ReplyAction="http://tempuri.org/IDocManager/DocumentLoadResponse")]
        TestProject1.ServiceReference.Doc DocumentLoad(System.Guid documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocManager/DocumentSave", ReplyAction="http://tempuri.org/IDocManager/DocumentSaveResponse")]
        TestProject1.ServiceReference.Doc DocumentSave(TestProject1.ServiceReference.Doc doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocManager/DocumentDelete", ReplyAction="http://tempuri.org/IDocManager/DocumentDeleteResponse")]
        void DocumentDelete(System.Guid documentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocManagerChannel : TestProject1.ServiceReference.IDocManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocManagerClient : System.ServiceModel.ClientBase<TestProject1.ServiceReference.IDocManager>, TestProject1.ServiceReference.IDocManager {
        
        public DocManagerClient() {
        }
        
        public DocManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestProject1.ServiceReference.Doc DocumentLoad(System.Guid documentId) {
            return base.Channel.DocumentLoad(documentId);
        }
        
        public TestProject1.ServiceReference.Doc DocumentSave(TestProject1.ServiceReference.Doc doc) {
            return base.Channel.DocumentSave(doc);
        }
        
        public void DocumentDelete(System.Guid documentId) {
            base.Channel.DocumentDelete(documentId);
        }
    }
}
